### ISSUE TITLE
Is it possible to clear Reveal output pane?

### ISSUE THREAD

**Issue by enesj** [vlaaad/reveal#12]
Thank you for this software!

Is there any way to clear Reveal output pane when needed?

**Comment by vlaaad** [comment]
Hi! Currently there is no way to do it, but I'm planning to add this ability in the future.

**Comment by enesj** [comment]
Thanks

**Comment by vlaaad** [comment]
Released `1.1.171` that adds <kbd>Ctrl L</kbd> as a shortcut for clearing the output panel. It uses <kbd>Ctrl</kbd> (instead of <kbd>⌘</kbd>) on Mac too for consistency.
