### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by aphsa** [vlaaad/reveal#18]
$ clj -Sdeps '{:deps {vlaaad/reveal {:mvn/version "1.2.180"}}}' -m vlaaad.reveal repl
WARNING: When invoking clojure.main, use -M
Clojure 1.10.1
user=> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by vlaaad.reveal.font$fn__1884$fn__1885 to method com.sun.javafx.scene.text.FontHelper.getNativeFont(javafx.scene.text.Font)
WARNING: Please consider reporting this to the maintainers of vlaaad.reveal.font$fn__1884$fn__1885
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by vlaaad** [comment]
I just released a fix (Free: `1.3.262`, Pro: `1.3.321`)
