### ISSUE TITLE
Definitions from files with CRLF echo \r to Reveal

### ISSUE THREAD

**Issue by rbeesley** [vlaaad/reveal#25]
For example on Windows:
```Clojure
(def example-def-with-CRLF
  {:hello "world"
   "foo" :bar})
```

Will output:
```
(def example-def-with-CRLF\r
  {:hello "world"\r
   "foo" :bar})
=> #'user/example-def-with-CRLF
```

nRepl just shows:
```
#'user/example-def-with-CRLF
clj꞉user꞉>
```

So Reveal is perhaps a better response in that it shows something, but for Windows, the carriage return wouldn't be expected in this case. Perhaps Reveal needs a line ending setting with an environment default if it isn't overwritten? I could see this being the desired statement because it *is* what is being sent, but it also doesn't seem *right*.

**Comment by vlaaad** [comment]
Thanks for report! There is a TODO in code about this issue: https://github.com/vlaaad/reveal/blob/master/src/vlaaad/reveal/stream.clj#L152

I agree it makes sense to hide those `\r`s. Contributions welcome!

**Comment by vlaaad** [comment]
Fixed in `1.3.194`

**Comment by rbeesley** [comment]
> I agree it makes sense to hide those `\r`s. Contributions welcome!

Thanks for doing this... I'm still working through CftBaT, so I'm probably not ready to make contributions yet... but I'm getting better.

**Comment by vlaaad** [comment]
Cheers!
