### ISSUE TITLE
#question How do I send error logs of a running server to reveal?

### ISSUE THREAD

**Issue by tlonist-sang** [vlaaad/reveal#32]
Hi, thanks for the great work.
I'm running a ring server with reitit(router), and I want to send the error logs to reveal. 

If I type directly into my local repl, reveal works great- it pretty prints the messages and does all sorts of stuffs for me. But it doesn't display any errors coming from the server - such as reitit coercion errors and SQL errors .. etc.

FYI, I'm running on local REPL with clojure.main, running with deps with parameters instructed in the introduction.
Do I need to add some configurations sending server errors to reveal?

**Comment by vlaaad** [comment]
Does your server use some logging library? Those usually log to stdout/stderr, so it's hard for Reveal to get access to those. You can try adding a listener for your logging framework that will `tap>` the incoming logs, this way Reveal will display them. See [e07](https://github.com/vlaaad/reveal/blob/master/examples/e07_timbre_tap_appender.clj) for an example.

**Comment by tlonist-sang** [comment]
late reply. works great, thanks!
