### ISSUE TITLE
Note on Leiningen

### ISSUE THREAD

**Issue by mtruyens** [vlaaad/reveal#9]
I have not yet jumped on the CLJ deps train, and use Leiningen. I am *very* interested to try out Reveal in my Lein-based main project, but am struggling with converting the CLJ-parameters to Lein. 

Any input?

**Comment by vlaaad** [comment]
Depends on your preferred repl type. IIRC lein uses nrepl by default, so supposedly you can just add a dev dependency on reveal and specify a middleware in the `.nrepl.edn` file as described [here](https://vlaaad.github.io/reveal/#nrepl-based-editors). I personally prefer socket repls, here is an example of using reveal entry points with leiningen:

1. project.clj:
   ```clj
   (defproject com.example/reveal "1.0.0-SNAPSHOT"
    :dependencies [[org.clojure/clojure "1.10.1"]]
    :profiles {:dev {:dependencies [[vlaaad/reveal "1.0.128"]]}})
   ```
2. shell:
   ```sh
   lein run -m vlaaad.reveal repl
   ```
